service: "serverless-client"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /

plugins:
  - serverless-webpack
  - serverless-offline
