service: serverless

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
  userController:
    handler: userController.handler
    events:
      - http: ANY /api/user


package:
  exclude:
    - node_modules/**
    - client/node_modules/**

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  contentCompression: 1024
  severless-offline:
    port: 8080
    webpackIncludeModules: true
  webpack:
    includeModules: true
    packager: "npm"